const properties = [
  // ── 1 BHK ─────────────────────────────────────────────────────────────────
  { id:1,  name:"Supertech Ecociti — 1 BHK",           location:"Sector 137, Noida",          price:"₹32 Lakh",     area:"620 sqft",  bhk:"1BHK",       status:"Ready to Move", budget_category:"under_50L", amenities:"Gym, Security, Park",              builder:"Supertech",  possession:"Immediate" },
  { id:2,  name:"Ajnara Homes — 1 BHK Studio",         location:"Noida Extension, Gr. Noida", price:"₹28 Lakh",     area:"540 sqft",  bhk:"1BHK",       status:"Ready to Move", budget_category:"under_50L", amenities:"24x7 Security, Club",              builder:"Ajnara",     possession:"Immediate" },
  { id:3,  name:"Puri Aanand Vilas — 1 BHK",           location:"Sector 81, Faridabad",       price:"₹35 Lakh",     area:"650 sqft",  bhk:"1BHK",       status:"Ready to Move", budget_category:"under_50L", amenities:"Pool, Gym, Children Play",          builder:"Puri",       possession:"Immediate" },

  // ── 2 BHK ─────────────────────────────────────────────────────────────────
  { id:4,  name:"Gaur City 2 — 2 BHK",                 location:"Noida Extension, Gr. Noida", price:"₹48 Lakh",     area:"950 sqft",  bhk:"2BHK",       status:"Ready to Move", budget_category:"under_50L", amenities:"Gym, Club, Pool, Tennis",          builder:"Gaursons",   possession:"Immediate" },
  { id:5,  name:"Amrapali Silicon City — 2 BHK",       location:"Sector 76, Noida",           price:"₹45 Lakh",     area:"905 sqft",  bhk:"2BHK",       status:"Ready to Move", budget_category:"under_50L", amenities:"Club, Gym, Badminton Court",        builder:"Amrapali",   possession:"Immediate" },
  { id:6,  name:"ATS Pristine — 2 BHK",                location:"Sector 150, Noida",          price:"₹72 Lakh",     area:"1150 sqft", bhk:"2BHK",       status:"Ready to Move", budget_category:"50L_1Cr",  amenities:"Olympic Pool, Gym, Spa",            builder:"ATS",        possession:"Immediate" },
  { id:7,  name:"Godrej Nest — 2 BHK",                 location:"Sector 150, Noida",          price:"₹88 Lakh",     area:"1200 sqft", bhk:"2BHK",       status:"Under Construction", budget_category:"50L_1Cr", amenities:"Jogging Track, Club, Pool",     builder:"Godrej",     possession:"Dec 2025"  },
  { id:8,  name:"Godrej South Estate — 2 BHK",         location:"Okhla, South Delhi",         price:"₹1.4 Crore",   area:"1200 sqft", bhk:"2BHK",       status:"Ready to Move", budget_category:"1Cr_2Cr",  amenities:"Rooftop Pool, Gym, Concierge",       builder:"Godrej",     possession:"Immediate" },
  { id:9,  name:"DLF Park Place — 2 BHK",              location:"Sector 54, Gurugram",        price:"₹1.6 Crore",   area:"1350 sqft", bhk:"2BHK",       status:"Ready to Move", budget_category:"1Cr_2Cr",  amenities:"Pool, Club, 24x7 Security, Garden",  builder:"DLF",        possession:"Immediate" },

  // ── 3 BHK ─────────────────────────────────────────────────────────────────
  { id:10, name:"ATS Pristine — 3 BHK Premium",        location:"Sector 150, Noida",          price:"₹85 Lakh",     area:"1450 sqft", bhk:"3BHK",       status:"Ready to Move", budget_category:"50L_1Cr",  amenities:"Olympic Pool, Gym, Spa, Club",       builder:"ATS",        possession:"Immediate" },
  { id:11, name:"DLF Skycourt — 3 BHK",                location:"Sector 86, Gurugram",        price:"₹95 Lakh",     area:"1600 sqft", bhk:"3BHK",       status:"Ready to Move", budget_category:"50L_1Cr",  amenities:"Clubhouse, Pool, Tennis",            builder:"DLF",        possession:"Immediate" },
  { id:12, name:"Sobha City — 3 BHK",                  location:"Sector 108, Gurugram",       price:"₹1.35 Crore",  area:"1800 sqft", bhk:"3BHK",       status:"Ready to Move", budget_category:"1Cr_2Cr",  amenities:"Resort-style Pool, Gym, Spa",        builder:"Sobha",      possession:"Immediate" },
  { id:13, name:"Emaar Palm Select — 3 BHK",           location:"Sector 77, Gurugram",        price:"₹1.55 Crore",  area:"1950 sqft", bhk:"3BHK",       status:"Ready to Move", budget_category:"1Cr_2Cr",  amenities:"Club, Pool, International School",   builder:"Emaar",      possession:"Immediate" },
  { id:14, name:"Prestige Falcon City — 3 BHK",        location:"Dwarka Expressway, Delhi",   price:"₹1.2 Crore",   area:"1700 sqft", bhk:"3BHK",       status:"Under Construction", budget_category:"1Cr_2Cr", amenities:"Sports Club, Pool, Gym",         builder:"Prestige",   possession:"Mar 2026"  },
  { id:15, name:"Tata New Haven — 3 BHK",              location:"Sector 72, Faridabad",       price:"₹78 Lakh",     area:"1380 sqft", bhk:"3BHK",       status:"Ready to Move", budget_category:"50L_1Cr",  amenities:"Gym, Pool, Children Park",           builder:"Tata",       possession:"Immediate" },

  // ── 4 BHK / Villa ─────────────────────────────────────────────────────────
  { id:16, name:"M3M Golf Estate — 4 BHK",             location:"Sector 65, Gurugram",        price:"₹2.1 Crore",   area:"3200 sqft", bhk:"4BHK+",      status:"Ready to Move", budget_category:"above_2Cr", amenities:"Private Garden, Golf View, Club",    builder:"M3M",        possession:"Immediate" },
  { id:17, name:"DLF Crest — 4 BHK Penthouse",        location:"Sector 54, Gurugram",        price:"₹3.5 Crore",   area:"4100 sqft", bhk:"4BHK+",      status:"Ready to Move", budget_category:"above_2Cr", amenities:"Private Terrace, Concierge, Pool",   builder:"DLF",        possession:"Immediate" },
  { id:18, name:"Emaar Palm Springs — 4 BHK Villa",   location:"Sector 54, Gurugram",        price:"₹4.8 Crore",   area:"5000 sqft", bhk:"4BHK+",      status:"Ready to Move", budget_category:"above_2Cr", amenities:"Private Pool, Golf View, Smart Home", builder:"Emaar",      possession:"Immediate" },
  { id:19, name:"Ansal API Highland Park — Villa",     location:"Sector 103, Gurugram",       price:"₹2.8 Crore",   area:"3800 sqft", bhk:"4BHK+",      status:"Ready to Move", budget_category:"above_2Cr", amenities:"Private Lawn, Club, 24x7 Security",  builder:"Ansal",      possession:"Immediate" },

  // ── Commercial ────────────────────────────────────────────────────────────
  { id:20, name:"Wave One — Office Space",             location:"Sector 18, Noida",           price:"₹85 Lakh",     area:"800 sqft",  bhk:"Commercial", status:"Ready to Move", budget_category:"50L_1Cr",  amenities:"High-Speed Lift, Parking, Cafeteria", builder:"Wave",       possession:"Immediate" },
  { id:21, name:"AIPL Business Club — Office",         location:"Sector 62, Gurugram",        price:"₹1.4 Crore",   area:"1000 sqft", bhk:"Commercial", status:"Ready to Move", budget_category:"1Cr_2Cr",  amenities:"Grade A Office, Metro Nearby",        builder:"AIPL",       possession:"Immediate" },
  { id:22, name:"Bhutani Cyber Courtyard — Shop",      location:"Sector 140A, Noida",         price:"₹45 Lakh",     area:"300 sqft",  bhk:"Commercial", status:"Ready to Move", budget_category:"under_50L", amenities:"High Street Retail, Food Court",      builder:"Bhutani",    possession:"Immediate" },
  { id:23, name:"World Trade Centre — Office",         location:"Barakhamba Road, Delhi",     price:"₹2.5 Crore",   area:"1500 sqft", bhk:"Commercial", status:"Ready to Move", budget_category:"above_2Cr", amenities:"Premium Grade A, Concierge, Parking", builder:"WTC",        possession:"Immediate" },
];

module.exports = properties;
